### ISSUE TITLE
固件集成度很好，iStore和内置软件源有bug

### ISSUE THREAD

**Issue by kerncoola** [1-1-2/OpenWrt-HC5661#4]
<img width="962" alt="iShot2022-08-06 00 18 07" src="https://user-images.githubusercontent.com/13283995/183119450-6a203a63-4435-488d-875a-d1b98f4e5004.png">
**opkg update**有部分failed。

<img width="789" alt="iShot2022-08-06 00 11 33" src="https://user-images.githubusercontent.com/13283995/183119467-03d9f5b1-a8d6-46a6-9733-ad8c1b8870fa.png">
iStore更新或安装软件提示错误。

**Comment by 1-1-2** [comment]
kenzo 源好像没有对应的ipk库，只在编译过程有用。
istore 好像是因为资源挂载在外网上的原因，需要科学，我没有深究这个。
