### ISSUE TITLE
无法指定commit

### ISSUE THREAD

**Issue by Huiaei** [1-1-2/OpenWrt-HC5661#6]
尝试了很久，在commit那栏填了，但是还是用的是latest。
是否填写问题？比如https://github.com/openwrt/openwrt/commit/f7541aecdc0658051f492016733a64a1de4904bd，我填的是f7541aecdc0658051f492016733a64a1de4904bd。

**Comment by 1-1-2** [comment]
排查了一下，应该是调用配置脚本的时候
https://github.com/1-1-2/OpenWrt-Custom/blob/090340a72d2dc11f75cab7ca9da343c581d18661/device-env.sh#L45

覆写了 actions 的参数，现在应该可以了

**Comment by Huiaei** [comment]
好的，现在好像没有问题了，非常感谢。
